 version: 0.1
 os: linux
 files:
     - source: /
       destination: /var/www/html
 hooks:
  AfterInstall:
     - location:script/install_nginx.sh
       timeout: 300
       runas: root
 ApplicationStart:
     - location:script/start_nginx.sh
       timeout: 300
       runas: root
